name: Deploy to Heroku

on:
  push:
    branches: [master]

jobs:
  # Label of the runner job
  postgres-setup:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.0', '4.2', '4.4']
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Copy .env file
        run: |
          cd backend && touch .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          echo MONGO_DB_URL=${{secrets.MONGO_DB_URL}} >> .env
          echo JWT_EXPIRATION=${{secrets.JWT_EXPIRATION}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          cat .env
      - name: Run install and Tests
        run: |
          cd backend && yarn install
          yarn run dev & sleep 10 && curl http://localhost:6000 && yarn test
          yarn run build
      - name: Set github credentials
        run: |
          ls -l
          git config user.email ${{secrets.USER_EMAIL}}
          git config user.name ${{secrets.USER_NAME}}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to dev
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_YARN_PRODUCTION: false
          HD_SECRET: ${{secrets.SECRET}}
          HD_MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}
          HD_JWT_EXPIRATION: ${{secrets.JWT_EXPIRATION}}
           